### ISSUE TITLE
Sound Test and Getting a Shield Stops Music in S3K.

### ISSUE THREAD

**Issue by Alriightyman** [flamewing/flamedriver#5]
Adding the Flamedriver to stock S3K presents 2 issues. 
1) When getting a shield the music immediately stops.  SFX still play and sound will resume through any means that plays a song (Boss, Invincibility stars, Super forms, etc.)

2) Play any sound in the Sound Test will not play any sounds and as above, stop all music. 

I also tested https://github.com/flamewing/skdisasm which includes the Flamedriver and it presents the same issues. 

Have tested this in Regen, Gens Kmod, and real hardware.

**Comment by flamewing** [comment]
I updated the referred disassembly with the remaining corrections. The issue is due to split music/SFX queue, to allow more songs and more SFX, which I forgot to account for in there.
